version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  fastapi-server:
    build:
      context: ../
      dockerfile: docker/pytest.Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./cov:/code/cov/
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - TESTING=1
      - POSTGRES_URL=postgresql://test:test@postgres:5432/test
      - TEST_POSTGRES_URL=postgresql://test:test@postgres:5432/test
