version: "3.9"
services:
  fastapi-server:
    build:
      context: ../
      dockerfile: docker/pytest.Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./cov:/code/cov/
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - TESTING=1