version: "3.9"
services:
  fastapi-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../src:/code/src
      - ../tests:/code/tests
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - TESTING=1
